spring.application.name=cinerex

api.security.token.secret=I7zJrH8dmTAwnR1Z3zsIUa9wfNZQNCIagplK/GXHRZw=

spring.datasource.url=jdbc:mysql://localhost:3306/cinerex
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
